### ISSUE TITLE
CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by arnstein** [Linaro/lava-server#12]
I am on Debian Stretch and have followed the installation guide [here](https://staging.validation.linaro.org/static/docs/v2/installing_on_debian.html#debian-installation). I have done `sudo lava-server manage createsuperuser --username $USERNAME --email=$EMAIL` but when I try to log in with the information I provided I get the following error:

> Forbidden (403)
> CSRF verification failed. Request aborted.
> You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.
> If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for 'same-origin' requests.
> 

Is this a bug or, more likely, an error in my setup? Either way, how can I fix it?

**Comment by ader1990** [comment]
Same happened to me, on Debian Stretch. I used Debian Jessie and all worked fine.
I have a step by step guide on how to install && configure Lava on Jessie: https://github.com/ader1990/configs/blob/master/Readme-LavaInstallation.md

Thank you,
Adrian Vladu

**Comment by arnstein** [comment]
Thank you very much for the quick reply. Although your reply is helpful, I do not find this solution satisfying. Surely there must be a way to make it work on Stretch?

**Comment by ader1990** [comment]
That would be a helpful response for me too.

Thank you,
Adrian Vladu

**Comment by mattface** [comment]
This isn't an official way of getting help with LAVA, but you're hitting a Django settings change for non-HTTPS installs.
https://validation.linaro.org/static/docs/v2/pipeline-debug.html#using-localhost-or-non-https-instance-url

For future reference, you're best bet for support is lava-users@lists.linaro.org

**Comment by arnstein** [comment]
Thank you very much! Will use the mailing list from now on.
