### ISSUE TITLE
setup.py data_files section

### ISSUE THREAD

**Issue by rosds** [Linaro/lava-server#4]
Hi, I was trying to install the project and then I realize the data_files where not being installed. When I check the setup.py file, I notice the call to the .extend of the data_files list. The return of this call is None which was the reason why "python setup.py install_data" was raising a not iterable exception.

You should replace the .extend(...) for a simple " + " list concatenation. That solved my problem.

**Comment by ghost** [comment]
Installing from setup.py is NOT supported. The code must be built as a package. There is a lot more that setup.py simply cannot do. Always use the packages or the developer build scripts.
